### ISSUE TITLE
Help with smote

### ISSUE THREAD

**Issue by michele2198** [rikhuijzer/Resample.jl#4]
Hi, I have difficulties in using this package. I have a dataframe with features (X) and a vector of binary outcomes (y), how can I apply smote? my gues would be: 

`[X1,y1]=smote(X,y,5,10)` or similar but doesn't work

**Comment by rikhuijzer** [comment]
Hi. Have you seen the tutorial at https://rikhuijzer.github.io/Resample.jl/dev/notebooks/smote/? 

Your guess is almost correct. Here is another example which is close to your situation. It samples two 2 points for the dataset with 3 points:

```julia
pkg> using DataFrames, Resample

julia> df = DataFrame(; X=1.0:3.0, Y=4.0:6.0)
3×2 DataFrame
 Row │ X        Y
     │ Float64  Float64
─────┼──────────────────
   1 │     1.0      4.0
   2 │     2.0      5.0
   3 │     3.0      6.0

julia> smote(df, 2) |> DataFrame
2×2 DataFrame
 Row │ X        Y
     │ Float64  Float64
─────┼──────────────────
   1 │ 2.76004  5.76004
   2 │ 1.08092  4.08092
```

**Comment by rikhuijzer** [comment]
Looking through the tutorial, maybe the confusion is about the dimensions. More than 2 dimensions is possible too. For example:

```julia
julia> df = DataFrame(; A=1.0:3.0, B=4.0:6.0, Y=7.0:9.0)
3×3 DataFrame
 Row │ A        B        Y
     │ Float64  Float64  Float64
─────┼───────────────────────────
   1 │     1.0      4.0      7.0
   2 │     2.0      5.0      8.0
   3 │     3.0      6.0      9.0

julia> smote(df, 2) |> DataFrame
2×3 DataFrame
 Row │ A        B        Y
     │ Float64  Float64  Float64
─────┼───────────────────────────
   1 │ 1.2228   4.2228   7.2228
   2 │ 1.13629  4.13629  7.13629
```
